-- MySQL Script generated by MySQL Workbench
-- Thu Jun  9 14:26:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema A2_3C_LuizAmancio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema A2_3C_LuizAmancio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `A2_3C_LuizAmancio` DEFAULT CHARACTER SET utf8 ;
USE `A2_3C_LuizAmancio` ;

-- -----------------------------------------------------
-- Table `A2_3C_LuizAmancio`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A2_3C_LuizAmancio`.`Funcionario` (
  `matricula` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A2_3C_LuizAmancio`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A2_3C_LuizAmancio`.`Cliente` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `renach` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A2_3C_LuizAmancio`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A2_3C_LuizAmancio`.`Marca` (
  `cd_Marca` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cd_Marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A2_3C_LuizAmancio`.`Modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A2_3C_LuizAmancio`.`Modelo` (
  `cd_Modelo` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `Marca_cd_Marca` INT NOT NULL,
  PRIMARY KEY (`cd_Modelo`),
  INDEX `fk_Modelo_Marca_idx` (`Marca_cd_Marca` ASC),
  CONSTRAINT `fk_Modelo_Marca`
    FOREIGN KEY (`Marca_cd_Marca`)
    REFERENCES `A2_3C_LuizAmancio`.`Marca` (`cd_Marca`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A2_3C_LuizAmancio`.`Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A2_3C_LuizAmancio`.`Carro` (
  `placa` VARCHAR(7) NOT NULL,
  `renavam` VARCHAR(45) NOT NULL,
  `ano` VARCHAR(4) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `kmInicial` DOUBLE NOT NULL,
  `Modelo_cd_Modelo` INT NOT NULL,
  PRIMARY KEY (`placa`),
  INDEX `fk_Carro_Modelo1_idx` (`Modelo_cd_Modelo` ASC),
  CONSTRAINT `fk_Carro_Modelo1`
    FOREIGN KEY (`Modelo_cd_Modelo`)
    REFERENCES `A2_3C_LuizAmancio`.`Modelo` (`cd_Modelo`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A2_3C_LuizAmancio`.`Locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A2_3C_LuizAmancio`.`Locacao` (
  `cdLocacao` INT NOT NULL,
  `dataLocacao` DATETIME NOT NULL,
  `dataDevolucao` DATE NOT NULL,
  `valorLocacao` DOUBLE NOT NULL,
  `Cliente_cpf` VARCHAR(11) NOT NULL,
  `Carro_placa` VARCHAR(7) NOT NULL,
  `Funcionario_matricula` INT NOT NULL,
  PRIMARY KEY (`cdLocacao`),
  INDEX `fk_Locacao_Cliente1_idx` (`Cliente_cpf` ASC) ,
  INDEX `fk_Locacao_Carro1_idx` (`Carro_placa` ASC) ,
  INDEX `fk_Locacao_Funcionario1_idx` (`Funcionario_matricula` ASC) ,
  CONSTRAINT `fk_Locacao_Cliente1`
    FOREIGN KEY (`Cliente_cpf`)
    REFERENCES `A2_3C_LuizAmancio`.`Cliente` (`cpf`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_Locacao_Carro1`
    FOREIGN KEY (`Carro_placa`)
    REFERENCES `A2_3C_LuizAmancio`.`Carro` (`placa`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `fk_Locacao_Funcionario1`
    FOREIGN KEY (`Funcionario_matricula`)
    REFERENCES `A2_3C_LuizAmancio`.`Funcionario` (`matricula`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
